name = "poultry-weight-tracker"
account_id = "607a4c8239664450331ee2c9de563318"
compatibility_date = "2026-01-01"
pages_build_output_dir = "dist"

[vars]
ENVIRONMENT = "production"
WORKERS_SUBDOMAIN = "shreedharg405.workers.dev"
